FROM node:14
WORKDIR /usr
COPY package.json ./
COPY tsconfig.json ./
COPY .env ./
COPY source ./source
RUN ls -a .
RUN npm install
RUN npm run build
# COPY .docker/wait-for-it.sh ./wait-for-it.sh
RUN ls -a .


FROM node:14
WORKDIR /usr
COPY package.json ./
RUN npm install --only=production
COPY --from=0 /usr/dist .
RUN ls -a
RUN npm install pm2 -g
EXPOSE 3000
CMD ["pm2-runtime","shared/index.js"]